PROBLEMSET5/urls.py
from django.contrib import admin
from django.urls import path, include # don't forget to import include

urlpatterns = [
    path('myapp/', include('myApp.urls')),
    path('admin/', admin.site.urls),
]

myApp/urls.py
from django.urls import path
from . import views

# a namespace for our app, this will become important in the Templates section
app_name = 'myApp'

# we call the path function to let Django know what of our Python function should be
# called when a certain URL has been entered.
# The name parameter is optional, but lets us later more conveniently link between pages.
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add_element, name='add_joke'),
    path('delete_all/', views.delete_all, name='delete_all'),
]

myApp/models.py
from django.db import models

class Element(models.Model):
    value = models.CharField(max_length=255)
    username = models.CharField(max_length=255, default='Mathuschan')
    id = models.AutoField(primary_key=True)


class Person(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Quote(models.Model):
    text = models.TextField()
    element = models.CharField(max_length=255, default="default_value", blank=True)

    person = models.ForeignKey(Person, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.text} - {self.person}"

myApp/forms.py
from django import forms
from .models import Quote

class QuoteForm(forms.ModelForm):
    class Meta:
        model = Quote
        fields = ('text', 'person')
        widgets = {
            'text': forms.Textarea(attrs={'rows': 3}),
            'person': forms.Select(attrs={'class': 'form-control'}),
        }

myApp/views.py
"""
from django.shortcuts import render, redirect
from myApp.models import Element
from django.contrib import messages

from django.http import JsonResponse
from myApp.models import Element, Person

def entry(request, id):
    element = Element.objects.get(id=id)
    data = {
        'id': element.id,
        'username': element.username,
        'value': element.value
    }
    return JsonResponse(data)


from .forms import QuoteForm

def add_joke(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = QuoteForm()

    # Ajouter cette ligne pour récupérer les personnes de la base de données
    persons = Person.objects.all()

    context = {
        'form': form,
        'persons': persons, # Ajouter cette variable au contexte
    }
    return render(request, 'myApp/add_joke.html', context)

from .models import Person, Quote
from .forms import QuoteForm

def add_joke(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            person_id = request.POST.get('person')
            person = Person.objects.get(pk=person_id)
            quote = form.save(commit=False)
            quote.person = person
            quote.save()
            return redirect('myApp:index')
    else:
        form = QuoteForm()
    return render(request, 'myApp/add_joke.html', {'form': form, 'persons': Person.objects.all()})



def index(request):
    elements = Element.objects.all()
    context = {'elements': elements}

    last_element_added_id = request.session.get('last_element_added', None)

    for element in elements:
        if element.id == last_element_added_id:
            element.is_last_added = True
        else:
            element.is_last_added = False

    return render(request, 'myapp/index.html', context)


def get_authors(request):
    persons = Person.objects.all()
    return render(request, 'app/authors.html', {'persons': persons})


def delete_all(request):
    Element.objects.all().delete()
    return redirect('myApp:index')
"""

from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Element, Person, Quote
from .forms import QuoteForm

def index(request):
    quotes = Quote.objects.all()
    context = {'quotes': quotes}
    return render(request, 'myApp/index.html', context)

from django.shortcuts import render
from django.http import HttpResponse

def add_element(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            person_id = request.POST.get('person')
            person = Person.objects.get(pk=person_id)
            quote = form.save(commit=False)
            quote.person = person
            quote.save()
            return redirect('myApp:index')
    else:
        form = QuoteForm()
    return render(request, 'myApp/add_joke.html', {'form': form, 'persons': Person.objects.all()})


def get_authors(request):
    authors = Person.objects.all()
    return render(request, 'myApp/authors.html', {'authors': authors})


def get_elements(request):
    elements = Quote.objects.all().order_by('id')
    elements_list = [{'element': elem.value, 'person': elem.person.name} for elem in elements]
    if len(elements_list) > 0:
        elements_list[-1]['is_last_added'] = True
    return render(request, 'myApp/index.html', {'elements': elements_list})


def delete_all(request):
    Element.objects.all().delete()
    return HttpResponseRedirect(reverse('myApp:index'))

myApp/templates/myApp/add_joke.html
<!DOCTYPE html>
<html>
<head>
  <title>Page d'entrée</title>
</head>
<body>
<h1>Page d'entrée</h1>
<form method="POST" action="{% url 'myApp:add_joke' %}">
  {% csrf_token %}
  <label for="element">Entrer un élément:</label>
  <input type="text" id="element" name="element">

  <label for="person">Choisir une personne :</label>
  <select id="person" name="person">
    {% for person in persons %}
    <option value="{{ person.id }}">{{ person.name }}</option>
    {% endfor %}
  </select>


  <button type="submit">Soumettre</button>
</form>
<script>
  // Rafraîchir la page après soumission du formulaire
  document.querySelector('form').addEventListener('submit', function() {
    location.reload();
  });
</script>
</body>
</html>

myApp/templates/myApp/index.html
<!--
<!DOCTYPE html>
<html>
<head>
    <title>Page de sortie</title>
</head>
<body>
<h1>Page de Blague</h1>
<p>Ajouter une blague :</p>
<button onclick="window.location.href='http://127.0.0.1:8000/myapp/add/'">Cliquez ici</button>
<br><br>
<form method="POST" action="{% url 'myApp:delete_all' %}">
    {% csrf_token %}
    <button type="submit">Supprimer tous les éléments</button>
</form>

{% if elements %}
<p>Les blagues ajoutées sont :</p>
<ul>
    {% for element in elements %}
    {% if element.is_last_added %}
    <li><strong>{{ element.id }} ->{{ element.username|upper }} -> {{ element.value }}</strong></li>
    {% else %}
    <li>{{ element.id }} ->{{ element.username|upper }} -> {{ element.value }}</li>
    {% endif %}
    {% endfor %}
</ul>
{% else %}
<p>Aucune blague n'a été ajoutée</p>
{% endif %}


</body>
</html>-->

<!DOCTYPE html>
<html>
<head>
    <title>Page de sortie</title>
</head>
<body>
<h1>Page de citation</h1>
<p>Ajouter une citation :</p>
<button onclick="window.location.href='http://127.0.0.1:8000/myapp/add/'">Cliquez ici</button>
<br><br>

{% if quotes %}
<p>Les citations ajoutées sont :</p>
<ul>
    {% for quote in quotes %}
    <li>{{ quote.text }} -> {{ quote.person }}</li>
    {% endfor %}
</ul>
{% else %}
<p>Aucune blague n'a été ajoutée</p>
{% endif %}


<form method="POST" action="{% url 'myApp:delete_all' %}">
    {% csrf_token %}
    <button type="submit">Supprimer tous les éléments</button>
</form>

</body>
</html>